environments:
  dev_env:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - midpipeline
      - devpipeline
pipelines:
  "build-pipeline":
    group: build-group
    materials:
      "gocd-test-master":
        git: https://github.com/alexIzual/gocd-test.git
        branch: master
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
                - exec: # indicates type of task
                    command: dotnet
                    working_directory: Microservice.Second/
                    arguments:
                      - "build"
      - unit_tests:
          jobs:
            unit_tests:
              tasks:
                - exec:
                    command: dotnet
                    working_directory: Microservice.Second/
                    arguments:
                      - "test"
  "deploy-pipeline": # definition of yaml-example pipeline
    group: deploy-group
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      upstream:
        # type is optional here, material type is implied based on presence of pipeline and stage fields
        # type: dependency
        pipeline: build-pipeline
        stage: unit_tests
    stages: # list of stages in order
      - build: # name of stage
          clean_workspace: true
          jobs:
            csharp: # name of the job
              resources:
                - net45
              artifacts:
                - build:
                    source: bin/
                    destination: build
                - test:
                    source: tests/
                    destination: test-reports/
              tabs:
                report: test-reports/index.html
              tasks: # ordered list of tasks to execute in job csharp
                - fetch:
                    pipeline: devpipeline
                    stage: build
                    job: build
                    source: test-bin/
                    destination: bin/
                - exec: # indicates type of task
                    command: make
                    arguments:
                      - "VERBOSE=true"
