format_version: 10
environments:
  dev_env:
    pipelines:
      - deploy-pipeline-f1
      - build-pipeline-f1
pipelines:
  build-pipeline-f1:
    group: build-group
    label_template: "${mygit[:8]}"
    materials:
      mygit:
        git: https://github.com/alexIzual/gocd-test.git
        branch: master
        blacklist:
          - Microservice.Second/**/*.*
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: dotnet
                    working_directory: Microservice.First/
                    arguments:
                      - "build"
      # - unit_tests:
      #     jobs:
      #       unit_tests:
      #         tasks:
      #           - exec:
      #               command: dotnet
      #               working_directory: Microservice.First/
      #               arguments:
      #                 - "test --verbosity d"
  deploy-pipeline-f1:
    group: deploy-group
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit:
        git: https://github.com/alexIzual/gocd-test.git
        branch: master
        blacklist:
          - Microservice.Second/**/*.*
      upstream:
        pipeline: build-pipeline-f1
        stage: build
    stages:
      - build:
          clean_workspace: true
          jobs:
            publish:
              tasks:
                - exec:
                    command: dotnet
                    arguments:
                      - "publish -c Release"
