format_version: 10
environments:
  dev_env:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
      - deploy-pipeline-s2
      - build-pipeline-s2
pipelines:
  build-pipeline-s2:
    group: build-group
    label_template: "${mygit[:8]}"
    materials:
      mygit:
        git: https://github.com/alexIzual/gocd-test.git
        branch: master
        whitelist:
          - Microservice.Second/**/*.*
    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: dotnet
                    working_directory: Microservice.Second/
                    arguments:
                      - "build"
      - unit_tests:
          jobs:
            unit_tests:
              tasks:
                - exec:
                    command: dotnet
                    working_directory: Microservice.Second/
                    arguments:
                      - "test --verbosity d"
  deploy-pipeline-s2:
    group: deploy-group
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit:
        git: https://github.com/alexIzual/gocd-test.git
        branch: master
        whitelist:
          - Microservice.Second/**/*.*
      upstream:
        pipeline: build-pipeline-s2
        stage: unit_tests
    stages:
      - build:
          approval: manual
          clean_workspace: true
          jobs:
            csharp:
              tasks:
                - exec:
                    command: dotnet
                    arguments:
                      - "publish -c Release"
